# setup postgres with PostGIS for geospatial data locally
version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: localeiq-db
    restart: always
    environment:
      POSTGRES_USER: localeiq
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: localeiq
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
