# Configuration for PostgreSQL
services:
  database:
    image: postgres:latest
    container_name: localeiq-db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - database_volume:/var/lib/postgresql

# Configuration for pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: localeiq-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
    depends_on:
      - database

# Define named volumes
volumes:
  database_volume:
  pgadmin_volume:
