[pytest]
minversion = 8.0
addopts = -ra -q -n auto
pythonpath = .
testpaths =
    culture/tests
    data/tests
    economic/tests
    geopolitical/tests
    language/tests
    shared/tests
    date_time/tests
