"""create core tables

Revision ID: 690501c32ae7
Revises: 
Create Date: 2025-12-13 09:07:01.341085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '690501c32ae7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False, comment='Raw country name from source'),
    sa.Column('iso_alpha_2', sa.String(length=2), nullable=True, comment="e.g., 'US', 'CA'"),
    sa.Column('iso_alpha_3', sa.String(length=3), nullable=True, comment="e.g., 'USA', 'CAN'"),
    sa.Column('iso_num', sa.String(length=3), nullable=True, comment="e.g., '840', '124'"),
    sa.Column('notes', sa.Text(), nullable=True, comment='Optional notes about the record'),
    sa.Column('source_name', sa.String(length=64), nullable=False, comment="'CLDR', 'Wikipedia', etc."),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze',
    comment='Raw country data from various sources'
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iso_639_1', sa.String(length=64), nullable=False, comment='ISO 639-1 two-letter code for major languages: en, zh, fr, etc.'),
    sa.Column('iso_639_2', sa.String(length=64), nullable=False, comment='ISO 639-2 three-letter code for wider range of languages including language groups: eng, chi, fre, etc.'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='English name of the language'),
    sa.Column('name_local', sa.String(length=256), nullable=True, comment='Native name of the language'),
    sa.Column('script', sa.String(length=32), nullable=True, comment='Script used in the language'),
    sa.Column('direction', sa.String(length=8), nullable=True, comment='Text direction of the language'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Optional notes about the record'),
    sa.Column('source_name', sa.String(length=64), nullable=False, comment="'CLDR', 'Wikipedia', etc."),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze',
    comment='Raw language data from various sources'
    )
    op.create_table('locale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=32), nullable=False, comment='BCP-47 language tag with optional script: es-MX, en-US, en-Latn-US, zh_Hans_CN'),
    sa.Column('language', sa.String(length=16), nullable=False, comment='Language code: es, en, zh'),
    sa.Column('script', sa.String(length=16), nullable=True, comment='Language script: Latn, Hans, Cyrl'),
    sa.Column('region', sa.String(length=16), nullable=True, comment='Region code: US, MX, CN'),
    sa.Column('source_name', sa.String(length=64), nullable=False, comment="'CLDR', 'Wikipedia', etc."),
    sa.Column('notes', sa.Text(), nullable=True, comment='Optional notes about the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag'),
    schema='bronze',
    comment='Canonical locale identifiers (BCP 47 / CLDR)'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locale', schema='bronze')
    op.drop_table('languages', schema='bronze')
    op.drop_table('countries', schema='bronze')
    # ### end Alembic commands ###
