"""add locale tag index

Revision ID: 56d59fc7a2d3
Revises: 690501c32ae7
Create Date: 2025-12-13 10:26:33.477392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56d59fc7a2d3'
down_revision: Union[str, Sequence[str], None] = '690501c32ae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_locale_tag', 'locale', ['tag'], unique=False, schema='bronze')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_locale_tag', table_name='locale', schema='bronze')
    # ### end Alembic commands ###
