"""

Revision ID: c232f1a9abbe
Revises: 
Create Date: 2025-12-24 21:35:36.105396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c232f1a9abbe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False, comment='Raw country name from source'),
    sa.Column('iso_alpha_2', sa.String(length=2), nullable=True, comment="e.g., 'US', 'CA'"),
    sa.Column('iso_alpha_3', sa.String(length=3), nullable=True, comment="e.g., 'USA', 'CAN'"),
    sa.Column('iso_num', sa.String(length=3), nullable=True, comment="e.g., '840', '124'"),
    sa.Column('notes', sa.Text(), nullable=True, comment='Optional notes about the record'),
    sa.Column('source_name', sa.String(length=64), nullable=False, comment="Source of the data: 'cldr', 'Wikipedia', etc."),
    sa.Column('source_version', sa.String(length=32), nullable=True, comment='Version of the source data, if applicable'),
    sa.Column('source_url', sa.String(length=256), nullable=True, comment='URL or location of the source data'),
    sa.Column('source_path', sa.String(length=128), nullable=True, comment='Path within the source data where this locale is defined, if applicable'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze',
    comment='Raw country data from various sources'
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=32), nullable=True, comment='Locale code associated with the language and determines label regionally'),
    sa.Column('language_code', sa.String(length=64), nullable=False, comment='Unique code representing the language from the source system'),
    sa.Column('label', sa.String(length=128), nullable=False, comment='Human-readable language label as asserted by the source'),
    sa.Column('source_category', sa.String(length=64), nullable=True, comment='Source-specific classification (opaque). Examples: menu.core, alt.variant'),
    sa.Column('assertion_type', sa.String(length=32), nullable=False, comment='Nature of the assertion (e.g., label, alias, variant, menu_hint)'),
    sa.Column('source_name', sa.String(length=64), nullable=False, comment="Source of the data: 'cldr', 'Wikipedia', etc."),
    sa.Column('source_version', sa.String(length=32), nullable=True, comment='Version of the source data, if applicable'),
    sa.Column('source_url', sa.String(length=256), nullable=True, comment='URL or location of the source data'),
    sa.Column('source_path', sa.String(length=128), nullable=True, comment='Path within the source data where this locale is defined, if applicable'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Optional notes about the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze',
    comment='Raw language data from various sources.'
    )
    op.create_table('locales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locale_tag', sa.String(length=32), nullable=True, comment='language tag: en, es-MX, en-US, en-Latn-US, zh_Hans_CN, zh'),
    sa.Column('language', sa.String(length=16), nullable=True, comment="Primary language subtag: 'en', 'es', 'zh'"),
    sa.Column('script', sa.String(length=16), nullable=True, comment="Optional script subtag: 'Latn', 'Hans', 'Cyrl'"),
    sa.Column('region', sa.String(length=16), nullable=True, comment="Optional region subtag: 'US', 'MX', 'CN'"),
    sa.Column('source_name', sa.String(length=64), nullable=False, comment="Source of the data: 'cldr', 'Wikipedia', etc."),
    sa.Column('source_version', sa.String(length=32), nullable=True, comment='Version of the source data, if applicable'),
    sa.Column('source_url', sa.String(length=256), nullable=True, comment='URL or location of the source data'),
    sa.Column('source_path', sa.String(length=128), nullable=True, comment='Path within the source data where this locale is defined, if applicable'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Optional notes about the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze',
    comment='Raw locale data from various sources.'
    )
    op.create_index('idx_locale_language', 'locales', ['language'], unique=False, schema='bronze')
    op.create_index('idx_locale_region', 'locales', ['region'], unique=False, schema='bronze')
    op.create_index('idx_locale_script', 'locales', ['script'], unique=False, schema='bronze')
    op.create_index('idx_locale_tag', 'locales', ['locale_tag'], unique=False, schema='bronze')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_locale_tag', table_name='locales', schema='bronze')
    op.drop_index('idx_locale_script', table_name='locales', schema='bronze')
    op.drop_index('idx_locale_region', table_name='locales', schema='bronze')
    op.drop_index('idx_locale_language', table_name='locales', schema='bronze')
    op.drop_table('locales', schema='bronze')
    op.drop_table('languages', schema='bronze')
    op.drop_table('countries', schema='bronze')
    # ### end Alembic commands ###
