"""create_country

Revision ID: a3bc22d6631a
Revises: 
Create Date: 2025-12-06 14:13:03.555109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3bc22d6631a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False, comment='Raw country name from source'),
    sa.Column('iso_alpha_2', sa.String(length=2), nullable=True, comment="e.g., 'US', 'CA'"),
    sa.Column('iso_alpha_3', sa.String(length=3), nullable=True, comment="e.g., 'USA', 'CAN'"),
    sa.Column('iso_num', sa.String(length=3), nullable=True, comment="e.g., '840', '124'"),
    sa.Column('source_name', sa.String(length=64), nullable=False, comment="'CLDR', 'Wikipedia', etc."),
    sa.Column('notes', sa.Text(), nullable=True, comment='Optional notes about the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze',
    comment='Raw country data from various sources'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('countries', schema='bronze')
    # ### end Alembic commands ###
